name: Download Video

on:
  schedule:
    - cron: "00 11 * * *"   #19:00
    - cron: "20 11 * * *"   #19:20
    - cron: "30 11 * * *"   #19:30
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PHP
      run: |
        sudo apt-get update
        sudo apt-get install -y php-cli

    - name: Fetch video URL and createdAt
      id: fetch_data
      run: |
        # 运行 PHP 脚本并输出结果
        php script.php > result.txt
        # 从 result.txt 提取 mp4Url 和 createdAt
        mp4Url=$(grep 'MP4 URL:' result.txt | sed 's/MP4 URL: //')
        createdAt=$(grep 'Created At:' result.txt | sed 's/Created At: //')
        echo "mp4Url=$mp4Url" >> $GITHUB_ENV
        echo "createdAt=$createdAt" >> $GITHUB_ENV

    - name: Create videos directory
      run: mkdir -p videos

    - name: Download video
      if: env.mp4Url != ''
      run: |
        # 下载视频并重命名
        curl -L ${{ env.mp4Url }} -o "videos/${{ env.createdAt }}.mp4"
        
    - name: Commit video to repository
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add videos/${{ env.createdAt }}.mp4
        git commit -m 'Add downloaded video'
        git push
