name: Daily Weather Job
on:
  schedule:
    - cron: "55 21 * * *"  #5:55
    - cron: "0 0 * * *"  #8:00
    - cron: "0 1 * * *"  #9:00
    - cron: "0 5 * * *"  #13:00
    - cron: "20 5 * * *"  #13:20
    - cron: "55 5 * * *"  #13:55
    - cron: "40 11 * * *"   #19:40
    - cron: "0 12 * * *"   #20:00
    - cron: "20 12 * * *"   #20:20
    - cron: "0 14 * * *"   #22:00
    - cron: "0 15 * * *"   #23:00
  workflow_dispatch:

  # 监听 hatq.yml 完成
  workflow_run:
    workflows: ["Download HATQ Video"]
    types:
      - completed

jobs:
  run-php-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Delete tq.txt File
      run: |
        if [ -f "php/tq.txt" ]; then
          rm -rf php/tq.txt
          git rm -r --cached php/tq.txt
          git commit -m "Delete tq.txt" || echo "No changes to commit"
          git push
        else
          echo "tq.txt not found, skipping deletion"
        fi
      env:
        PAT: ${{ secrets.GITHUBS_TOKEN }}
    
    - name: Create php directory and tq.txt
      run: |
        mkdir -p php
        touch php/tq.txt

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # 设置 PHP 版本

    #- name: Print working directory
      #run: pwd

    - name: Run PHP script
      #env:
          #HATQ_JSON_URL: ${{ secrets.HATQ_JSON_URL }}
      run: |
        php php/list.php  # 运行你的 PHP 脚本

    - name: Check git status before commit
      run: |
        git status
        git diff --cached
        git log -1

    - name: Add and Commit tq.txt changes
      run: |
        git add php/tq.txt
        git status
        git commit -m "Update tq.txt with new URL" || echo "No changes to commit"

    #- name: Pull latest changes and rebase
      #run: |
        #git pull --rebase
        #git status
        #git log -1

    - name: Push changes to repository
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN }}

    - name: Check git status after push
      run: |
        git status
        git log -1

    - name: Access autoUpdate tqURL
      run: |
        #curl -X GET ${{ secrets.AUTOUPDATE_URL }}
        curl -X GET "${{ secrets.AUTOUPDATE_URL_DSI }}?gh=${{ github.actor }}&type=tq"
        curl -X GET "${{ secrets.AUTOUPDATE_URL_ZPCT }}?gh=${{ github.actor }}&type=tq"
        curl -X GET "${{ secrets.AUTOUPDATE_URL_DS }}?gh=${{ github.actor }}&type=tq"
        curl -X GET "${{ secrets.AUTOUPDATE_URL }}?gh=${{ github.actor }}&type=tq"
  
