name: Daily Job
on:
  schedule:
    - cron: "0 21 * * *"  #5:00
    - cron: "30 7 * * *"   #15:30  
  workflow_dispatch:

jobs:
  run-php-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # 设置 PHP 版本

    - name: Install dependencies
      run: |
        composer install  # 如果你有依赖管理文件 composer.json

    - name: Run PHP script
      run: |
        php php/list.php  # 运行你的 PHP 脚本
