name: Daily Job
on:
  schedule:
    - cron: "0 21 * * *"  #5:00
    - cron: "30 7 * * *"   #15:30  
  workflow_dispatch:

jobs:
  run-html-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 检出代码到工作空间

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 指定Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install

    - name: Run list.py script
      run: |
        python py/list.py  # 运行你的 Python 脚本
