name: Daily Wheather Job
on:
  schedule:
    - cron: "0 0 * * *"  #8:00
    - cron: "0 1 * * *"  #9:00
    - cron: "20 5 * * *"  #13:20
    - cron: "20 12 * * *"   #20:20
  workflow_dispatch:

jobs:
  run-php-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # 设置 PHP 版本

    #- name: Print working directory
      #run: pwd


    - name: Run PHP script
      run: |
        php php/list.php  # 运行你的 PHP 脚本

    - name: Commit and Push result.txt changes
      run: |
        git add php/result.txt
        git commit -m "Update result.txt with new URL" || echo "No changes to commit"
        git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN }}
