name: Download HATQ Video

on:
  workflow_dispatch:
  
jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run PHP script to set video URL
      id: set_video_url
      run: |
        video_url=$(php php/hatq.php | grep 'video_url=' | cut -d '=' -f 2)
        echo "::set-output name=video_url::$video_url"

    - name: Output video_url to console
      run: |
        echo "The video URL is: ${{ steps.set_video_url.outputs.video_url }}"

    - name: Download video
      run: |
        mkdir -p videos
        curl -L ${{ steps.set_video_url.outputs.video_url }} -o videos/hatq.mp4

    - name: Commit video to repository
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # 添加文件到暂存区
        git add videos/hatq.mp4
        
        # 检查是否有更改
        if [[ `git status --porcelain` ]]; then
          git commit -m 'Add downloaded video'
          git push
        else
          echo "No changes to commit"
        fi
